### ISSUE TITLE
Go Modules

### ISSUE THREAD

**Issue by chimanjain** [caio/go-tdigest#33]
Do you plan to add Go Modules support
When I am using this module, it is showing it as incompatible module
```
github.com/caio/go-tdigest v3.1.0+incompatible
```

**Comment by caio** [comment]
Hello,

I had no plans, but I think it's simple enough. Lemme see if I can do this in a few minutes

Out of curiosity, does this impact you anyhow or is it just the `+incompatible` thing that bothers you? The benefit I can see from modules here is test dependency pruning only.

**Comment by caio** [comment]
I have it on a branch: https://github.com/caio/go-tdigest/tree/modules

So `go get github.com/caio/go-tdigest/v3@modules` works as expected, but when it lands on master it whines about being unable to find the package.

Leaving this as is for now since I have no idea what to do and have zero interest in maintaining multiple major versions. Will revisit sometime in the future.

I'm happy to take a pull request if you know the right way of getting this to work.

**Comment by caio** [comment]
Figured it out: had to bump to v4 🤷

It should work now if you update the module path to `github.com/caio/go-tdigest/v4` and `go mod tidy`

**Comment by caio** [comment]
[New release tagged](https://github.com/caio/go-tdigest/releases/tag/v4.0.0). I'm closing this as done. Thanks for opening the issue!

Would still like to hear if this was impacting you in any way, if you are able to share.

**Comment by chimanjain** [comment]
Thanks for the quick resolve. I just wanted it to have support for go modules.
